version: "3.9"
services:
  app:
    container_name: oclettings
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
#    environment:
#      - SETTINGS_MODE=$DEV_SETTINGS
#    volumes:
#      - static:/usr/src/app/static
#      - $DEV_HOME:/usr/src/app/oc
    ports:
      - "80:8000"
    networks:
      - default
#    command: python3 manage.py runserver
    command: gunicorn --env DJANGO_SETTINGS_MODULE=oc_lettings_site.settings oc_lettings_site.wsgi -w 4 -b :8000 --reload --timeout 300

networks:
  default:
