# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-deploy:
    docker:
      - image: docker:stable  # Image de base pour les jobs

    steps:
      - checkout  # Récupérer le code depuis GitHub

      - setup_remote_docker:  # Configuration de Docker
          version: 20.10.23

      - run:
          name: Build and Push Docker Image
          command: |
            docker login $DO_REGISTRY -u $DO_API_TOKEN -p $DO_API_TOKEN
            docker build -t $DO_REGISTRY/oclettings .

      - run:
          name: Push to Docker Hub
          command: |
            docker login $DO_REGISTRY -u $DO_API_TOKEN -p $DO_API_TOKEN
            doctl registry login --expiry-seconds 600
            docker push $DO_REGISTRY/oclettings:latest

#      - deploy:
#          name: Deploy to Digital Ocean
#          command: |
#            ssh $DROPLET_USER@$DROPLET_IP -i ~/.ssh/circleci "docker pull $DO_REGISTRY/oclettings:latest"
#            ssh $DROPLET_USER@$DROPLET_IP -i ~/.ssh/circleci "docker-compose -f /usr/src/app/docker-compose.yml up -d"

##            docker build -t $DO_REGISTRY/oclettings:latest .

# Orchestrate our job run sequence
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main
